//export const CREATE_DRAWING = "CREATE_DRAWING";
export const LOAD_DRAWING_SUCCESS = "LOAD_DRAWING_SUCCESS";
export const CREATE_DRAWING_SUCCESS = "CREATE_DRAWING_SUCCESS";
export const UPDATE_DRAWING_SUCCESS = "UPDATE_DRAWING_SUCCESS";
export const DELETE_DRAWING_SUCCESS = "DELETE_DRAWING_SUCCESS";

//export const LOAD_AUTHORS_SUCCESS = "LOAD_AUTHORS_SUCCESS";

